### ISSUE TITLE
Not working for me. 

### ISSUE THREAD

**Issue by politicus** [saschadiercks/little-helpers#1]
Hi, 

I do not get the same results as your example as I get this :
`font-size: em.75em;	/* 12px / 16px */`

I didn't set any parent value. Once the output is put out my cursor is placed between ".75" and "em".

I tried with different values without setting any parent value: 

With 100:
`font-size: em6.25em;	/* 100px / 16px */`

With 6: 
font-size: em.375em;	/* 6px / 16px */

The cursor was never placed at the right place in the output. 

Maybe I forgot a setting?

**Comment by saschadiercks** [comment]
Hi,
it seems, that the workflow is working in general, but is not triggered the correct way. I know, there was another user with a similar problem. Please try changing the keyword-trigger from 'em#' to something different. You can change this setting by opening the settings of Alfred. Then open "workflows" and select "pixelsToEm". Here you can change the keyword-trigger by double-clicking the first element in the workflow.
This might solve your problem.

**Comment by politicus** [comment]
It didn't solved the problem. 

I added a keyword in the "Keyword" trigger. It is not perfect as the cursor is till misplaced in the output but I will consider it as case closed.

Thank you.

**Comment by saschadiercks** [comment]
I poked aroud a bit an realized, that snippet keywords aren't exported, so it is nessecary to set them up, before this workflow is working fine. Alfred V3.4 or aboe is rquired too. I updated the readme to avoid conflicts in the future.
Thanks for  letting me know about the bug :)

**Comment by politicus** [comment]
For information, I have Alfred 3 v3.5 (868).
